insert into scienziati (nome) values('Albert Einstein (1879 - 1955)');
insert into scienziati (nome) values('Isaac Newton (1643 - 1727)');
insert into scienziati (nome) values('Stephen Hawking (1942- 2018)');
insert into scienziati (nome) values('Marie Curie (1867 - 1934)');
insert into scienziati (nome) values('Galileo Galilei (1564 - 1642)');
insert into scienziati (nome) values('Blaise Pascal (1623 - 1662)');
insert into scienziati (nome) values('Charles Darwin (1809 - 1882)');
insert into scienziati (nome) values('Nicolaus Copernico (1473 - 1543)');
insert into scienziati (nome) values('Benjamin Franklin (1706 - 1790)');
insert into scienziati (nome) values('Alexander Fleming (1881 - 1955)');
insert into scienziati (nome) values('Johannes Kepler (1571 - 1630)');
insert into scienziati (nome) values('Louis Pasteur (1822 - 1895)');
insert into scienziati (nome) values('Gregor Mendel (1822 - 1884)');
insert into scienziati (nome) values('Michael Faraday (1791 - 1867)');
insert into scienziati (nome) values('Max Planck (1858 - 1947)');
insert into scienziati (nome) values('Thomas Alva Edison (1847 - 1931)');
insert into scienziati (nome) values('Archimede di Siracusa (287 a.C. - 212 a.C.)');
insert into scienziati (nome) values('Leonardo da Vinci (1452 - 1519)');
insert into scienziati (nome) values('Louis Gay-Lussac (1778 - 1850)');
insert into scienziati (nome) values('Nikola Tesla (1856 - 1943)');
insert into scienziati (nome) values('Rudolf Hertz (1857 - 1894)');
insert into scienziati (nome) values('Ibn al-Haytham (964 - 1040)');
insert into scienziati (nome) values('Robert Hooke (1635 - 1703)');
insert into scienziati (nome) values('Santiago Ramón y Cajal (1852 - 1934)');
insert into scienziati (nome) values('Aristotele (384 a.C.-322 a.C.)');
insert into scienziati (nome) values('Pierre Simon Laplace (1749 - 1827)');
insert into scienziati (nome) values('Miguel Servet (1509 - 1553)');
insert into scienziati (nome) values('Erwin Schrodinger (1887 - 1961)');
insert into scienziati (nome) values('Severo Ochoa (1905 - 1993)');
insert into scienziati (nome) values('Karl Landsteiner (1868 - 1943)');
insert into scienziati (nome) values('Alfred Nobel (1833 - 1896)');
insert into scienziati (nome) values('Werner Karl Heisenberg (1901 - 1976)');
insert into scienziati (nome) values('Carl Friedrich Gauss (1777 - 1855)');
insert into scienziati (nome) values('Tim Berners-Lee (1955)');
insert into scienziati (nome) values('Pitagora (579 a.C. - 475 a.C.)');
insert into scienziati (nome) values('Sofia Kovalévskaya (1850 - 1891)');
insert into scienziati (nome) values('John Dalton (1766 - 1844)');
insert into scienziati (nome) values('James Dewey Watson (1928)');
insert into scienziati (nome) values('René Descartes (1596 - 1650)');
insert into scienziati (nome) values('Robert Boyle (1627 - 1691)          ');
insert into scienziati (nome) values('Gottfried Leibniz');
insert into scienziati (nome) values('Peter Higgs');
insert into scienziati (nome) values('Georg Simon Ohm');
insert into scienziati (nome) values('Isacco Asimov');
insert into scienziati (nome) values('Alexander Graham Bell');
insert into scienziati (nome) values('Niels Bohr');
insert into scienziati (nome) values('Mario Molina');
insert into scienziati (nome) values('Alessandro Volta');
insert into scienziati (nome) values('Guillermo Marconi');
insert into scienziati (nome) values('Joseph Fourier');
insert into scienziati (nome) values('Richard Feynman');
insert into scienziati (nome) values('Ernest Rutherford');
insert into scienziati (nome) values('Francis Crick');
insert into scienziati (nome) values('Edwin Hubble');
insert into scienziati (nome) values('Rosalind Franklin');
insert into scienziati (nome) values('Enrico Fermi');
insert into scienziati (nome) values('Carlos Linneo');
insert into scienziati (nome) values('Paul Dirac');
insert into scienziati (nome) values('Linus Pauling');
insert into scienziati (nome) values('Robert Oppenheimer');
insert into scienziati (nome) values('Rachel Carson');
insert into scienziati (nome) values('Antoine Lavoisier');
insert into scienziati (nome) values('James Clerk Maxwell');
insert into scienziati (nome) values('Heinrich Rudolf Hertz');
insert into scienziati (nome) values('William Thomson');